# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - uses: cachix/install-nix-action@v10
      with:
        # For install-nix-action v11 (which is failing for some reason): nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          extra-substituters = https://hydra.iohk.io
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

    - uses: cachix/cachix-action@v6
      with:
        name: mzabani
        skipPush: true

    - name: Build codd
      run: nix-build --option extra-substituters https://hydra.iohk.io -A codd.components.exes.codd-exe

    - name: Run tests
      run: nix-shell --option extra-substituters https://hydra.iohk.io --run "./scripts/run-tests.sh"